### ISSUE TITLE
Unable to accurately recognize the text in the picture.

### ISSUE THREAD

**Issue by Hanxven** [chainsx/BigStudyRenameBot#1]
I tried to recognize a QingNianDaXueXi screenshot, but it didn't work.

**Comment by chainsx** [comment]
This robot can upload QingNianDaXueXi screenshots as files to a QQ group , and this is a plugin for `nonebot2` , you may try to setup `cqhttp` and `nonebot2` runtime environment.

**Comment by chainsx** [comment]
But not run this Python script directly.
